paths:
  openagenda_events: "ressources/evenements-publics-openagenda.json"
  faiss_index_file: "src/database/faiss_index.idx"
  document_chunck_file: "src/database/document_chunks.pkl"
  rag_prompt_file: "src/rag/rag_prompt.txt"

models:
  embeddings_model: "BAAI/bge-m3"      #alternatives : "nomic-ai/nomic-embed-text-v1.5", "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
  llm_model: "open-mistral-nemo"
  evaluation_embeddings_model: "BAAI/bge-m3"
  evaluation_chat_model: "ministral-8b-2512"

indexer:
  chunk_size: 1500
  chunk_overlap: 150
  embedding_batch_size: 32
  search_k: 5
  similarity_threshold : 0.5